/**
 * Account Status
 */
export const ACCOUNT_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  ACTIVE: 'active'
}

/**
 * Account Invitation By
 */
export const ACCOUNT_INVITATION_BY = {
  SYSTEM: 'system',
  USER: 'user'
}

/**
 * Account Responsibility Types
 */
export const ACCOUNT_RESPONSIBILITY = {
  EA: 'Environment Agency – Area Programme Team',
  PSO: 'Environment Agency – Partnership & Strategic Overview Team',
  RMA: 'Risk Management Authority (RMA)'
}

/**
 * Account Validation Codes
 */
export const ACCOUNT_VALIDATION_CODES = {
  STATUS_REQUIRED: 'VALIDATION_ACCOUNT_STATUS_REQUIRED',
  STATUS_INVALID: 'VALIDATION_ACCOUNT_STATUS_INVALID',
  USER_ID_REQUIRED: 'VALIDATION_USER_ID_REQUIRED',
  USER_ID_INVALID: 'VALIDATION_USER_ID_INVALID',
  FIRST_NAME_REQUIRED: 'VALIDATION_FIRST_NAME_REQUIRED',
  FIRST_NAME_TOO_LONG: 'VALIDATION_FIRST_NAME_TOO_LONG',
  LAST_NAME_REQUIRED: 'VALIDATION_LAST_NAME_REQUIRED',
  LAST_NAME_TOO_LONG: 'VALIDATION_LAST_NAME_TOO_LONG',
  JOB_TITLE_REQUIRED: 'VALIDATION_JOB_TITLE_REQUIRED',
  JOB_TITLE_TOO_LONG: 'VALIDATION_JOB_TITLE_TOO_LONG',
  ORGANISATION_REQUIRED: 'VALIDATION_ORGANISATION_REQUIRED',
  ORGANISATION_TOO_LONG: 'VALIDATION_ORGANISATION_TOO_LONG',
  TELEPHONE_REQUIRED: 'VALIDATION_TELEPHONE_REQUIRED',
  TELEPHONE_TOO_LONG: 'VALIDATION_TELEPHONE_TOO_LONG',
  TELEPHONE_INVALID_FORMAT: 'VALIDATION_TELEPHONE_INVALID_FORMAT',
  RESPONSIBILITY_REQUIRED: 'VALIDATION_RESPONSIBILITY_REQUIRED',
  RESPONSIBILITY_INVALID: 'VALIDATION_RESPONSIBILITY_INVALID',
  ADMIN_FLAG_INVALID: 'VALIDATION_ADMIN_FLAG_INVALID',
  AREAS_REQUIRED: 'VALIDATION_AREAS_REQUIRED',
  AREA_ID_REQUIRED: 'VALIDATION_AREA_ID_REQUIRED',
  AREA_ID_INVALID: 'VALIDATION_AREA_ID_INVALID',
  PRIMARY_FLAG_INVALID: 'VALIDATION_PRIMARY_FLAG_INVALID',
  EMAIL_DISPOSABLE: 'VALIDATION_EMAIL_DISPOSABLE',
  EMAIL_DOMAIN_INVALID: 'VALIDATION_EMAIL_DOMAIN_INVALID',
  EMAIL_DUPLICATE: 'VALIDATION_EMAIL_DUPLICATE'
}

/**
 * Account Error Codes
 */
export const ACCOUNT_ERROR_CODES = {
  RETRIEVAL_FAILED: 'ACCOUNTS_RETRIEVAL_FAILED',
  UPSERT_FAILED: 'ACCOUNTS_UPSERT_FAILED',
  APPROVAL_FAILED: 'ACCOUNTS_APPROVAL_FAILED',
  DELETE_FAILED: 'ACCOUNTS_DELETE_FAILED',
  RESEND_INVITATION_FAILED: 'ACCOUNTS_RESEND_INVITATION_FAILED',
  USER_NOT_FOUND: 'ACCOUNT_USER_NOT_FOUND',
  NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  UNAUTHORIZED: 'ACCOUNT_UNAUTHORIZED',
  EMAIL_DUPLICATE: 'ACCOUNT_EMAIL_DUPLICATE',
  INVALID_STATUS: 'ACCOUNT_INVALID_STATUS',
  INVALID_AREA_IDS: 'ACCOUNT_INVALID_AREA_IDS',
  AREA_RESPONSIBILITY_MISMATCH: 'ACCOUNT_AREA_RESPONSIBILITY_MISMATCH'
}
