/**
 * Area Validation Codes
 */
export const AREA_VALIDATION_CODES = {
  ID_REQUIRED: 'VALIDATION_AREA_ID_REQUIRED',
  TYPE_REQUIRED: 'VALIDATION_AREA_TYPE_REQUIRED',
  TYPE_INVALID: 'VALIDATION_AREA_TYPE_INVALID',
  NAME_REQUIRED: 'VALIDATION_AREA_NAME_REQUIRED',
  NAME_TOO_SHORT: 'VALIDATION_AREA_NAME_TOO_SHORT',
  NAME_TOO_LONG: 'VALIDATION_AREA_NAME_TOO_LONG',
  IDENTIFIER_REQUIRED: 'VALIDATION_AREA_IDENTIFIER_REQUIRED',
  PARENT_ID_REQUIRED: 'VALIDATION_AREA_PARENT_ID_REQUIRED',
  SUBTYPE_REQUIRED: 'VALIDATION_AREA_SUBTYPE_REQUIRED',
  DATE_INVALID: 'VALIDATION_AREA_DATE_INVALID'
}
