/**
 * Authentication Validation Codes
 */
export const AUTH_VALIDATION_CODES = {
  // Email validation
  EMAIL_REQUIRED: 'VALIDATION_EMAIL_REQUIRED',
  EMAIL_INVALID_FORMAT: 'VALIDATION_EMAIL_INVALID_FORMAT',
  EMAIL_TOO_LONG: 'VALIDATION_EMAIL_TOO_LONG',

  // Password validation
  PASSWORD_REQUIRED: 'VALIDATION_PASSWORD_REQUIRED',
  PASSWORD_MIN_LENGTH: 'VALIDATION_PASSWORD_MIN_LENGTH',
  PASSWORD_MAX_LENGTH: 'VALIDATION_PASSWORD_MAX_LENGTH',
  PASSWORD_MISMATCH: 'VALIDATION_PASSWORD_MISMATCH',

  // Token validation
  TOKEN_REQUIRED: 'TOKEN_REQUIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  TOKEN_TYPE_REQUIRED: 'VALIDATION_TOKEN_TYPE_REQUIRED',
  TOKEN_TYPE_INVALID: 'VALIDATION_TOKEN_TYPE_INVALID'
}

/**
 * Authentication Error Codes
 */
export const AUTH_ERROR_CODES = {
  ACCOUNT_PENDING: 'AUTH_ACCOUNT_PENDING',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  ACCOUNT_SUPPORT: 'AUTH_ACCOUNT_SUPPORT',
  ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  ACCOUNT_SUPPORT_UNLOCK: 'AUTH_ACCOUNT_SUPPORT_UNLOCK',
  LAST_ATTEMPT_WARNING: 'AUTH_LAST_ATTEMPT_WARNING',
  ACCOUNT_NOT_FOUND: 'AUTH_ACCOUNT_NOT_FOUND',
  SESSION_MISMATCH: 'AUTH_SESSION_MISMATCH',
  TOKEN_EXPIRED_OR_INVALID: 'AUTH_TOKEN_EXPIRED_INVALID',
  RESET_TOKEN_EXPIRED_OR_INVALID: 'AUTH_RESET_TOKEN_EXPIRED_INVALID',
  INVITATION_TOKEN_EXPIRED_OR_INVALID: 'AUTH_INVITATION_TOKEN_EXPIRED_INVALID',
  PASSWORD_WAS_USED_PREVIOUSLY: 'AUTH_PASSWORD_WAS_USED_PREVIOUSLY',
  SESSION_ALREADY_INVALIDATED: 'SESSION_ALREADY_INVALIDATED'
}

/**
 * Token Types
 */
export const TOKEN_TYPES = {
  RESET: 'RESET',
  INVITATION: 'INVITATION'
}
