export const PROJECT_TYPES = {
  DEF: 'DEF',
  REP: 'REP',
  REF: 'REF',
  HCR: 'HCR',
  STR: 'STR',
  STU: 'STU',
  ELO: 'ELO'
}

export const PROJECT_INTERVENTION_TYPES = {
  NFM: 'NFM',
  SUDS: 'SUDS',
  PFR: 'PFR',
  OTHER: 'Other'
}

export const PROJECT_RISK_TYPES = {
  FLUVIAL: 'fluvial_flooding',
  TIDAL: 'tidal_flooding',
  GROUNDWATER: 'groundwater_flooding',
  SURFACE_WATER: 'surface_water_flooding',
  SEA: 'sea_flooding',
  RESERVOIR: 'reservoir_flooding',
  COASTAL_EROSION: 'coastal_erosion'
}

export const URGENCY_REASONS = {
  NOT_URGENT: 'not_urgent',
  STATUTORY_NEED: 'statutory_need',
  LEGAL_NEED: 'legal_need',
  HEALTH_AND_SAFETY: 'health_and_safety',
  EMERGENCY_WORKS: 'emergency_works',
  TIME_LIMITED: 'time_limited'
}

export const CONFIDENCE_LEVELS = {
  HIGH: 'high',
  MEDIUM_HIGH: 'medium_high',
  MEDIUM_LOW: 'medium_low',
  LOW: 'low',
  NOT_APPLICABLE: 'not_applicable'
}

export const PROJECT_STATUS = {
  DRAFT: 'draft',
  SUBMITTED: 'submitted',
  COMPLETED: 'completed',
  ARCHIVED: 'archived'
}

export const PROJECT_VALIDATION_MESSAGES = {
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  INVALID_DATA: 'INVALID_DATA',
  NOT_ALLOWED_TO_CREATE: 'NOT_ALLOWED_TO_CREATE',
  NOT_ALLOWED_TO_UPDATE: 'NOT_ALLOWED_TO_UPDATE',
  AREA_IS_NOT_ALLOWED: 'AREA_IS_NOT_ALLOWED',
  PROJECT_ID_REQUIRED: 'PROJECT_ID_REQUIRED',
  PROJECT_ID_INVALID: 'PROJECT_ID_INVALID',
  REFERENCE_NUMBER_REQUIRED: 'REFERENCE_NUMBER_REQUIRED',
  REFERENCE_NUMBER_INVALID_FORMAT: 'REFERENCE_NUMBER_INVALID_FORMAT',
  NAME_REQUIRED: 'PROJECT_NAME_REQUIRED',
  NAME_INVALID_FORMAT: 'PROJECT_NAME_INVALID',
  NAME_DUPLICATE: 'PROJECT_NAME_DUPLICATE',
  AREA_ID_REQUIRED: 'AREA_ID_REQUIRED',
  AREA_ID_INVALID: 'AREA_ID_INVALID',
  PROJECT_TYPE_REQUIRED: 'PROJECT_TYPE_REQUIRED',
  PROJECT_TYPE_INVALID: 'PROJECT_TYPE_INVALID',
  PROJECT_INTERVENTION_TYPE_REQUIRED: 'PROJECT_INTERVENTION_TYPE_REQUIRED',
  PROJECT_INTERVENTION_TYPE_INVALID: 'PROJECT_INTERVENTION_TYPE_INVALID',
  PROJECT_MAIN_INTERVENTION_TYPE_REQUIRED:
    'PROJECT_MAIN_INTERVENTION_TYPE_REQUIRED',
  PROJECT_MAIN_INTERVENTION_TYPE_INVALID:
    'PROJECT_MAIN_INTERVENTION_TYPE_INVALID',
  FINANCIAL_START_YEAR_REQUIRED: 'FINANCIAL_START_YEAR_REQUIRED',
  FINANCIAL_START_YEAR_SHOULD_BE_IN_FUTURE:
    'FINANCIAL_START_YEAR_SHOULD_BE_IN_FUTURE',
  FINANCIAL_START_YEAR_INVALID: 'FINANCIAL_START_YEAR_INVALID',
  FINANCIAL_START_YEAR_SHOULD_BE_LESS_THAN_END_YEAR:
    'FINANCIAL_START_YEAR_SHOULD_BE_LESS_THAN_END_YEAR',
  FINANCIAL_END_YEAR_REQUIRED: 'FINANCIAL_END_YEAR_REQUIRED',
  FINANCIAL_END_YEAR_INVALID: 'FINANCIAL_END_YEAR_INVALID',
  FINANCIAL_END_YEAR_SHOULD_BE_GREATER_THAN_START_YEAR:
    'FINANCIAL_END_YEAR_SHOULD_BE_GREATER_THAN_START_YEAR',
  FINANCIAL_END_YEAR_SHOULD_BE_IN_FUTURE:
    'FINANCIAL_END_YEAR_SHOULD_BE_IN_FUTURE',
  MONTH_REQUIRED: 'MONTH_REQUIRED',
  MONTH_INVALID: 'MONTH_INVALID',
  YEAR_REQUIRED: 'YEAR_REQUIRED',
  YEAR_INVALID: 'YEAR_INVALID',
  DATE_IN_PAST: 'DATE_IN_PAST',
  DATE_BEFORE_FINANCIAL_START: 'DATE_BEFORE_FINANCIAL_START',
  DATE_AFTER_FINANCIAL_START: 'DATE_AFTER_FINANCIAL_START',
  DATE_AFTER_FINANCIAL_END: 'DATE_AFTER_FINANCIAL_END',
  DATE_BEFORE_PREVIOUS_STAGE: 'DATE_BEFORE_PREVIOUS_STAGE',
  COULD_START_EARLY_REQUIRED: 'COULD_START_EARLY_REQUIRED',
  COULD_START_EARLY_INVALID: 'COULD_START_EARLY_INVALID',
  RISKS_REQUIRED: 'RISKS_REQUIRED',
  RISKS_INVALID: 'RISKS_INVALID',
  MAIN_RISK_REQUIRED: 'MAIN_RISK_REQUIRED',
  MAIN_RISK_INVALID: 'MAIN_RISK_INVALID',
  NO_PROPERTIES_AT_FLOOD_RISK_REQUIRED: 'NO_PROPERTIES_AT_FLOOD_RISK_REQUIRED',
  NO_PROPERTIES_AT_FLOOD_RISK_INVALID: 'NO_PROPERTIES_AT_FLOOD_RISK_INVALID',
  PROPERTY_VALUE_INVALID: 'PROPERTY_VALUE_INVALID',
  PROPERTY_VALUE_REQUIRED: 'PROPERTY_VALUE_REQUIRED',
  NO_PROPERTIES_AT_COASTAL_EROSION_RISK_REQUIRED:
    'NO_PROPERTIES_AT_COASTAL_EROSION_RISK_REQUIRED',
  NO_PROPERTIES_AT_COASTAL_EROSION_RISK_INVALID:
    'NO_PROPERTIES_AT_COASTAL_EROSION_RISK_INVALID',
  PERCENT_PROPERTIES_20_PERCENT_DEPRIVED_INVALID:
    'PERCENT_PROPERTIES_20_PERCENT_DEPRIVED_INVALID',
  PERCENT_PROPERTIES_20_PERCENT_DEPRIVED_MIN:
    'PERCENT_PROPERTIES_20_PERCENT_DEPRIVED_MIN',
  PERCENT_PROPERTIES_20_PERCENT_DEPRIVED_MAX:
    'PERCENT_PROPERTIES_20_PERCENT_DEPRIVED_MAX',
  PERCENT_PROPERTIES_20_PERCENT_DEPRIVED_PRECISION:
    'PERCENT_PROPERTIES_20_PERCENT_DEPRIVED_PRECISION',
  PERCENT_PROPERTIES_40_PERCENT_DEPRIVED_INVALID:
    'PERCENT_PROPERTIES_40_PERCENT_DEPRIVED_INVALID',
  PERCENT_PROPERTIES_40_PERCENT_DEPRIVED_MIN:
    'PERCENT_PROPERTIES_40_PERCENT_DEPRIVED_MIN',
  PERCENT_PROPERTIES_40_PERCENT_DEPRIVED_MAX:
    'PERCENT_PROPERTIES_40_PERCENT_DEPRIVED_MAX',
  PERCENT_PROPERTIES_40_PERCENT_DEPRIVED_PRECISION:
    'PERCENT_PROPERTIES_40_PERCENT_DEPRIVED_PRECISION',
  CURRENT_FLOOD_RISK_REQUIRED: 'CURRENT_FLOOD_RISK_REQUIRED',
  CURRENT_FLOOD_RISK_INVALID: 'CURRENT_FLOOD_RISK_INVALID',
  CURRENT_FLOOD_SURFACE_WATER_RISK_REQUIRED:
    'CURRENT_FLOOD_SURFACE_WATER_RISK_REQUIRED',
  CURRENT_FLOOD_SURFACE_WATER_RISK_INVALID:
    'CURRENT_FLOOD_SURFACE_WATER_RISK_INVALID',
  CURRENT_COASTAL_EROSION_RISK_REQUIRED:
    'CURRENT_COASTAL_EROSION_RISK_REQUIRED',
  CURRENT_COASTAL_EROSION_RISK_INVALID: 'CURRENT_COASTAL_EROSION_RISK_INVALID',
  APPROACH_REQUIRED: 'APPROACH_REQUIRED',
  APPROACH_MAX_LENGTH: 'APPROACH_MAX_LENGTH',
  URGENCY_REASON_REQUIRED: 'URGENCY_REASON_REQUIRED',
  URGENCY_REASON_INVALID: 'URGENCY_REASON_INVALID',
  URGENCY_DETAILS_REQUIRED: 'URGENCY_DETAILS_REQUIRED',
  URGENCY_DETAILS_MAX_LENGTH: 'URGENCY_DETAILS_MAX_LENGTH',
  CONFIDENCE_HOMES_BETTER_PROTECTED_REQUIRED:
    'CONFIDENCE_HOMES_BETTER_PROTECTED_REQUIRED',
  CONFIDENCE_HOMES_BETTER_PROTECTED_INVALID:
    'CONFIDENCE_HOMES_BETTER_PROTECTED_INVALID',
  CONFIDENCE_HOMES_BY_GATEWAY_FOUR_REQUIRED:
    'CONFIDENCE_HOMES_BY_GATEWAY_FOUR_REQUIRED',
  CONFIDENCE_HOMES_BY_GATEWAY_FOUR_INVALID:
    'CONFIDENCE_HOMES_BY_GATEWAY_FOUR_INVALID',
  CONFIDENCE_SECURED_PARTNERSHIP_FUNDING_REQUIRED:
    'CONFIDENCE_SECURED_PARTNERSHIP_FUNDING_REQUIRED',
  CONFIDENCE_SECURED_PARTNERSHIP_FUNDING_INVALID:
    'CONFIDENCE_SECURED_PARTNERSHIP_FUNDING_INVALID',
  ENVIRONMENTAL_BENEFITS_REQUIRED: 'ENVIRONMENTAL_BENEFITS_REQUIRED',
  ENVIRONMENTAL_BENEFITS_INVALID: 'ENVIRONMENTAL_BENEFITS_INVALID',
  ENVIRONMENTAL_BENEFITS_GATE_REQUIRED: 'ENVIRONMENTAL_BENEFITS_GATE_REQUIRED',
  ENVIRONMENTAL_BENEFITS_GATE_INVALID: 'ENVIRONMENTAL_BENEFITS_GATE_INVALID',
  ENVIRONMENTAL_BENEFITS_QUANTITY_REQUIRED:
    'ENVIRONMENTAL_BENEFITS_QUANTITY_REQUIRED',
  ENVIRONMENTAL_BENEFITS_QUANTITY_INVALID:
    'ENVIRONMENTAL_BENEFITS_QUANTITY_INVALID',
  ENVIRONMENTAL_BENEFITS_QUANTITY_MIN: 'ENVIRONMENTAL_BENEFITS_QUANTITY_MIN'
}

export const PROPOSAL_ERROR_MESSAGES = {
  NAME_VALIDATION_ERROR: 'PROJECT_NAME_VALIDATION_ERROR'
}

/**
 * Project validation levels
 */
export const PROJECT_VALIDATION_LEVELS = {
  INITIAL_SAVE: 'INITIAL_SAVE',
  PROJECT_NAME: 'PROJECT_NAME',
  PROJECT_AREA: 'PROJECT_AREA',
  PROJECT_TYPE: 'PROJECT_TYPE',
  FINANCIAL_START_YEAR: 'FINANCIAL_START_YEAR',
  FINANCIAL_END_YEAR: 'FINANCIAL_END_YEAR',
  START_OUTLINE_BUSINESS_CASE: 'START_OUTLINE_BUSINESS_CASE',
  COMPLETE_OUTLINE_BUSINESS_CASE: 'COMPLETE_OUTLINE_BUSINESS_CASE',
  AWARD_CONTRACT: 'AWARD_CONTRACT',
  START_CONSTRUCTION: 'START_CONSTRUCTION',
  READY_FOR_SERVICE: 'READY_FOR_SERVICE',
  COULD_START_EARLY: 'COULD_START_EARLY',
  EARLIEST_WITH_GIA: 'EARLIEST_WITH_GIA',
  RISK: 'RISK',
  MAIN_RISK: 'MAIN_RISK',
  PROPERTY_AFFECTED_FLOODING: 'PROPERTY_AFFECTED_FLOODING',
  PROPERTY_AFFECTED_COASTAL_EROSION: 'PROPERTY_AFFECTED_COASTAL_EROSION',
  TWENTY_PERCENT_DEPRIVED: 'TWENTY_PERCENT_DEPRIVED',
  FORTY_PERCENT_DEPRIVED: 'FORTY_PERCENT_DEPRIVED',
  CURRENT_FLOOD_RISK: 'CURRENT_FLOOD_RISK',
  CURRENT_FLOOD_SURFACE_WATER_RISK: 'CURRENT_FLOOD_SURFACE_WATER_RISK',
  CURRENT_COASTAL_EROSION_RISK: 'CURRENT_COASTAL_EROSION_RISK',
  APPROACH: 'APPROACH',
  URGENCY_REASON: 'URGENCY_REASON',
  URGENCY_DETAILS: 'URGENCY_DETAILS',
  CONFIDENCE_HOMES_BETTER_PROTECTED: 'CONFIDENCE_HOMES_BETTER_PROTECTED',
  CONFIDENCE_HOMES_BY_GATEWAY_FOUR: 'CONFIDENCE_HOMES_BY_GATEWAY_FOUR',
  CONFIDENCE_SECURED_PARTNERSHIP_FUNDING:
    'CONFIDENCE_SECURED_PARTNERSHIP_FUNDING',
  ENVIRONMENTAL_BENEFITS: 'ENVIRONMENTAL_BENEFITS',
  INTERTIDAL_HABITAT: 'INTERTIDAL_HABITAT',
  HECTARES_OF_INTERTIDAL_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_INTERTIDAL_HABITAT_CREATED_OR_ENHANCED',
  WOODLAND: 'WOODLAND',
  HECTARES_OF_WOODLAND_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_WOODLAND_HABITAT_CREATED_OR_ENHANCED',
  WET_WOODLAND: 'WET_WOODLAND',
  HECTARES_OF_WET_WOODLAND_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_WET_WOODLAND_HABITAT_CREATED_OR_ENHANCED',
  WETLAND_OR_WET_GRASSLAND: 'WETLAND_OR_WET_GRASSLAND',
  HECTARES_OF_WETLAND_OR_WET_GRASSLAND_CREATED_OR_ENHANCED:
    'HECTARES_OF_WETLAND_OR_WET_GRASSLAND_CREATED_OR_ENHANCED',
  GRASSLAND: 'GRASSLAND',
  HECTARES_OF_GRASSLAND_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_GRASSLAND_HABITAT_CREATED_OR_ENHANCED',
  PONDS_LAKES: 'PONDS_LAKES',
  HECTARES_OF_POND_OR_LAKE_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_POND_OR_LAKE_HABITAT_CREATED_OR_ENHANCED',
  ARABLE_LAND: 'ARABLE_LAND',
  HECTARES_OF_ARABLE_LAND_LAKE_HABITAT_CREATED_OR_ENHANCED:
    'HECTARES_OF_ARABLE_LAND_LAKE_HABITAT_CREATED_OR_ENHANCED',
  COMPREHENSIVE_RESTORATION: 'COMPREHENSIVE_RESTORATION',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_COMPREHENSIVE:
    'KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_COMPREHENSIVE',
  PARTIAL_RESTORATION: 'PARTIAL_RESTORATION',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_PARTIAL:
    'KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_PARTIAL',
  CREATE_HABITAT_WATERCOURSE: 'CREATE_HABITAT_WATERCOURSE',
  KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_SINGLE:
    'KILOMETRES_OF_WATERCOURSE_ENHANCED_OR_CREATED_SINGLE'
}

/**
 * Timeline validation levels (subset of validation levels)
 */
export const TIMELINE_VALIDATION_LEVELS = [
  PROJECT_VALIDATION_LEVELS.START_OUTLINE_BUSINESS_CASE,
  PROJECT_VALIDATION_LEVELS.COMPLETE_OUTLINE_BUSINESS_CASE,
  PROJECT_VALIDATION_LEVELS.AWARD_CONTRACT,
  PROJECT_VALIDATION_LEVELS.START_CONSTRUCTION,
  PROJECT_VALIDATION_LEVELS.READY_FOR_SERVICE,
  PROJECT_VALIDATION_LEVELS.EARLIEST_WITH_GIA
]

/**
 * Timeline field configuration mapping
 * Maps validation levels to their corresponding month/year field names
 */
export const TIMELINE_FIELD_CONFIG = {
  [PROJECT_VALIDATION_LEVELS.START_OUTLINE_BUSINESS_CASE]: {
    month: 'startOutlineBusinessCaseMonth',
    year: 'startOutlineBusinessCaseYear',
    name: 'Start Outline Business Case'
  },
  [PROJECT_VALIDATION_LEVELS.COMPLETE_OUTLINE_BUSINESS_CASE]: {
    month: 'completeOutlineBusinessCaseMonth',
    year: 'completeOutlineBusinessCaseYear',
    name: 'Complete Outline Business Case'
  },
  [PROJECT_VALIDATION_LEVELS.AWARD_CONTRACT]: {
    month: 'awardContractMonth',
    year: 'awardContractYear',
    name: 'Award Contract'
  },
  [PROJECT_VALIDATION_LEVELS.START_CONSTRUCTION]: {
    month: 'startConstructionMonth',
    year: 'startConstructionYear',
    name: 'Start Construction'
  },
  [PROJECT_VALIDATION_LEVELS.READY_FOR_SERVICE]: {
    month: 'readyForServiceMonth',
    year: 'readyForServiceYear',
    name: 'Ready for Service'
  },
  [PROJECT_VALIDATION_LEVELS.EARLIEST_WITH_GIA]: {
    month: 'earliestWithGiaMonth',
    year: 'earliestWithGiaYear',
    name: 'Earliest With GIA'
  }
}

/**
 * Project Error Codes
 */
export const PROJECT_ERROR_CODES = {
  RETRIEVAL_FAILED: 'PROJECTS_RETRIEVAL_FAILED',
  DELETE_FAILED: 'PROJECTS_DELETE_FAILED',
  NOT_FOUND: 'PROJECT_NOT_FOUND',
  INVALID_AREA_IDS: 'PROJECT_INVALID_AREA_IDS',
  INVALID_STATE: 'PROJECT_INVALID_STATE'
}
