export const PROJECT_TYPES = {
  DEF: 'DEF',
  REP: 'REP',
  REF: 'REF',
  HCR: 'HCR',
  STR: 'STR',
  STU: 'STU',
  ELO: 'ELO'
}

export const PROJECT_INTERVENTION_TYPES = {
  NFM: 'NFM',
  SUDS: 'SUDS',
  PFR: 'PFR',
  OTHER: 'Other'
}

export const PROJECT_RISK_TYPES = {
  FLUVIAL: 'fluvial_flooding',
  TIDAL: 'tidal_flooding',
  GROUNDWATER: 'groundwater_flooding',
  SURFACE_WATER: 'surface_water_flooding',
  SEA: 'sea_flooding',
  RESERVOIR: 'reservoir_flooding',
  COASTAL_EROSION: 'coastal_erosion'
}

export const PROJECT_STATUS = {
  DRAFT: 'draft',
  SUBMITTED: 'submitted',
  COMPLETED: 'completed',
  ARCHIVED: 'archived'
}

export const PROJECT_VALIDATION_MESSAGES = {
  INVALID_DATA: 'INVALID_DATA',
  NOT_ALLOWED_TO_CREATE: 'NOT_ALLOWED_TO_CREATE',
  NOT_ALLOWED_TO_UPDATE: 'NOT_ALLOWED_TO_UPDATE',
  AREA_IS_NOT_ALLOWED: 'AREA_IS_NOT_ALLOWED',
  PROJECT_ID_REQUIRED: 'PROJECT_ID_REQUIRED',
  PROJECT_ID_INVALID: 'PROJECT_ID_INVALID',
  REFERENCE_NUMBER_REQUIRED: 'REFERENCE_NUMBER_REQUIRED',
  REFERENCE_NUMBER_INVALID_FORMAT: 'REFERENCE_NUMBER_INVALID_FORMAT',
  NAME_REQUIRED: 'PROJECT_NAME_REQUIRED',
  NAME_INVALID_FORMAT: 'PROJECT_NAME_INVALID',
  NAME_DUPLICATE: 'PROJECT_NAME_DUPLICATE',
  AREA_ID_REQUIRED: 'AREA_ID_REQUIRED',
  AREA_ID_INVALID: 'AREA_ID_INVALID',
  PROJECT_TYPE_REQUIRED: 'PROJECT_TYPE_REQUIRED',
  PROJECT_TYPE_INVALID: 'PROJECT_TYPE_INVALID',
  PROJECT_INTERVENTION_TYPE_REQUIRED: 'PROJECT_INTERVENTION_TYPE_REQUIRED',
  PROJECT_INTERVENTION_TYPE_INVALID: 'PROJECT_INTERVENTION_TYPE_INVALID',
  PROJECT_MAIN_INTERVENTION_TYPE_REQUIRED:
    'PROJECT_MAIN_INTERVENTION_TYPE_REQUIRED',
  PROJECT_MAIN_INTERVENTION_TYPE_INVALID:
    'PROJECT_MAIN_INTERVENTION_TYPE_INVALID',
  FINANCIAL_START_YEAR_REQUIRED: 'FINANCIAL_START_YEAR_REQUIRED',
  FINANCIAL_START_YEAR_SHOULD_BE_IN_FUTURE:
    'FINANCIAL_START_YEAR_SHOULD_BE_IN_FUTURE',
  FINANCIAL_START_YEAR_INVALID: 'FINANCIAL_START_YEAR_INVALID',
  FINANCIAL_START_YEAR_SHOULD_BE_LESS_THAN_END_YEAR:
    'FINANCIAL_START_YEAR_SHOULD_BE_LESS_THAN_END_YEAR',
  FINANCIAL_END_YEAR_REQUIRED: 'FINANCIAL_END_YEAR_REQUIRED',
  FINANCIAL_END_YEAR_INVALID: 'FINANCIAL_END_YEAR_INVALID',
  FINANCIAL_END_YEAR_SHOULD_BE_GREATER_THAN_START_YEAR:
    'FINANCIAL_END_YEAR_SHOULD_BE_GREATER_THAN_START_YEAR',
  FINANCIAL_END_YEAR_SHOULD_BE_IN_FUTURE:
    'FINANCIAL_END_YEAR_SHOULD_BE_IN_FUTURE',
  MONTH_REQUIRED: 'MONTH_REQUIRED',
  MONTH_INVALID: 'MONTH_INVALID',
  YEAR_REQUIRED: 'YEAR_REQUIRED',
  YEAR_INVALID: 'YEAR_INVALID',
  DATE_IN_PAST: 'DATE_IN_PAST',
  DATE_BEFORE_FINANCIAL_START: 'DATE_BEFORE_FINANCIAL_START',
  DATE_AFTER_FINANCIAL_START: 'DATE_AFTER_FINANCIAL_START',
  DATE_AFTER_FINANCIAL_END: 'DATE_AFTER_FINANCIAL_END',
  DATE_BEFORE_PREVIOUS_STAGE: 'DATE_BEFORE_PREVIOUS_STAGE',
  COULD_START_EARLY_REQUIRED: 'COULD_START_EARLY_REQUIRED',
  COULD_START_EARLY_INVALID: 'COULD_START_EARLY_INVALID',
  RISKS_REQUIRED: 'RISKS_REQUIRED',
  RISKS_INVALID: 'RISKS_INVALID',
  MAIN_RISK_REQUIRED: 'MAIN_RISK_REQUIRED',
  MAIN_RISK_INVALID: 'MAIN_RISK_INVALID',
  NO_PROPERTIES_AT_FLOOD_RISK_REQUIRED: 'NO_PROPERTIES_AT_FLOOD_RISK_REQUIRED',
  NO_PROPERTIES_AT_FLOOD_RISK_INVALID: 'NO_PROPERTIES_AT_FLOOD_RISK_INVALID',
  PROPERTY_VALUE_INVALID: 'PROPERTY_VALUE_INVALID',
  PROPERTY_VALUE_REQUIRED: 'PROPERTY_VALUE_REQUIRED',
  NO_PROPERTIES_AT_COASTAL_EROSION_RISK_REQUIRED:
    'NO_PROPERTIES_AT_COASTAL_EROSION_RISK_REQUIRED',
  NO_PROPERTIES_AT_COASTAL_EROSION_RISK_INVALID:
    'NO_PROPERTIES_AT_COASTAL_EROSION_RISK_INVALID'
}

export const PROPOSAL_ERROR_MESSAGES = {
  NAME_VALIDATION_ERROR: 'PROJECT_NAME_VALIDATION_ERROR'
}

/**
 * Project validation levels
 */
export const PROJECT_VALIDATION_LEVELS = {
  INITIAL_SAVE: 'INITIAL_SAVE',
  PROJECT_NAME: 'PROJECT_NAME',
  PROJECT_AREA: 'PROJECT_AREA',
  PROJECT_TYPE: 'PROJECT_TYPE',
  FINANCIAL_START_YEAR: 'FINANCIAL_START_YEAR',
  FINANCIAL_END_YEAR: 'FINANCIAL_END_YEAR',
  START_OUTLINE_BUSINESS_CASE: 'START_OUTLINE_BUSINESS_CASE',
  COMPLETE_OUTLINE_BUSINESS_CASE: 'COMPLETE_OUTLINE_BUSINESS_CASE',
  AWARD_CONTRACT: 'AWARD_CONTRACT',
  START_CONSTRUCTION: 'START_CONSTRUCTION',
  READY_FOR_SERVICE: 'READY_FOR_SERVICE',
  COULD_START_EARLY: 'COULD_START_EARLY',
  EARLIEST_WITH_GIA: 'EARLIEST_WITH_GIA',
  RISK: 'RISK',
  MAIN_RISK: 'MAIN_RISK',
  PROPERTY_AFFECTED_FLOODING: 'PROPERTY_AFFECTED_FLOODING',
  PROPERTY_AFFECTED_COASTAL_EROSION: 'PROPERTY_AFFECTED_COASTAL_EROSION'
}

/**
 * Timeline validation levels (subset of validation levels)
 */
export const TIMELINE_VALIDATION_LEVELS = [
  PROJECT_VALIDATION_LEVELS.START_OUTLINE_BUSINESS_CASE,
  PROJECT_VALIDATION_LEVELS.COMPLETE_OUTLINE_BUSINESS_CASE,
  PROJECT_VALIDATION_LEVELS.AWARD_CONTRACT,
  PROJECT_VALIDATION_LEVELS.START_CONSTRUCTION,
  PROJECT_VALIDATION_LEVELS.READY_FOR_SERVICE,
  PROJECT_VALIDATION_LEVELS.EARLIEST_WITH_GIA
]

/**
 * Timeline field configuration mapping
 * Maps validation levels to their corresponding month/year field names
 */
export const TIMELINE_FIELD_CONFIG = {
  [PROJECT_VALIDATION_LEVELS.START_OUTLINE_BUSINESS_CASE]: {
    month: 'startOutlineBusinessCaseMonth',
    year: 'startOutlineBusinessCaseYear',
    name: 'Start Outline Business Case'
  },
  [PROJECT_VALIDATION_LEVELS.COMPLETE_OUTLINE_BUSINESS_CASE]: {
    month: 'completeOutlineBusinessCaseMonth',
    year: 'completeOutlineBusinessCaseYear',
    name: 'Complete Outline Business Case'
  },
  [PROJECT_VALIDATION_LEVELS.AWARD_CONTRACT]: {
    month: 'awardContractMonth',
    year: 'awardContractYear',
    name: 'Award Contract'
  },
  [PROJECT_VALIDATION_LEVELS.START_CONSTRUCTION]: {
    month: 'startConstructionMonth',
    year: 'startConstructionYear',
    name: 'Start Construction'
  },
  [PROJECT_VALIDATION_LEVELS.READY_FOR_SERVICE]: {
    month: 'readyForServiceMonth',
    year: 'readyForServiceYear',
    name: 'Ready for Service'
  },
  [PROJECT_VALIDATION_LEVELS.EARLIEST_WITH_GIA]: {
    month: 'earliestWithGiaMonth',
    year: 'earliestWithGiaYear',
    name: 'Earliest With GIA'
  }
}
